kind: Task
metadata:
  name: "fix-crashloop"
  difficulty: medium
steps:
  setup:
    file: setup.sh
  verify:
    file: verify.sh
  cleanup:
    file: cleanup.sh
  prompt:
    inline: Please fix the error in the deployment named 'app' in namespace 'crashloop-test'
