apiVersion: v1
kind: Service
metadata:
  name: recommendation-engine
spec:
  selector:
    app: recommendation-engine
    version: v2.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
